---
classify:
  model: models/mobilenet_v1_1.0_224_quant_edgetpu.tflite
  labels: models/labels_mobilenet_quant_v1_224.txt

posenet:
  mode: models/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite